[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#2979ff"
backgroundColor="#F8F8FF"
secondaryBackgroundColor="#F8F8FF"
textColor="#151B25"
font="sans-serif"

[runner]
fastReruns = true

[client]
showErrorDetails = false


