[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#2979ff"
backgroundColor="#181C24"
secondaryBackgroundColor="#232B36"
textColor="#F8F8FF"
font="sans-serif"

[runner]
fastReruns = true

[client]
showErrorDetails = false


